server:
  host: "127.0.0.1"
  port: 8080

routes:
  - path: /get
    target: https://httpbin.org

  - path: /api/v1
    target: https://echo.behzadan.com/

logging:
  level: info
  format: Compact
  console:
    enabled: true
    colors: false

debug: true
