# x86_64 target with musl (statically linked)
[target.x86_64-unknown-linux-musl]
rustflags = [
  "-C", "target-feature=+crt-static",
  "-C", "link-arg=-lgcc"
]

# aarch64 (ARM64) target with musl (statically linked)
[target.aarch64-unknown-linux-musl]
rustflags = [
  "-C", "target-feature=+crt-static",
  "-C", "link-arg=-lgcc"
]
